### PR TITLE
reset IFS back to default in ensure_redhat_gpgkey_installed.sh

### LINKED ISSUE #2511: eval statement in function replace_or_append is broken by setting IFS=$'\n'
#### Description of problem:
Remediation for xccdf_org.ssgproject.content_rule_ensure_gpgcheck_globally_activated fails with error: sed -i: command not found

#### SCAP Security Guide Version:
0.1.36-1.el7.centos 

#### Operating System Version:
CentOS Linux release 7.4.1708 (Core) 

#### Steps to Reproduce:

1. Generate a remediation script for the NIST 800-171 profile
2. Run the single script that has all 359 remediations in it.

#### Actual Results:
sed -i: command not found

#### Expected Results:
Remediations are successfully applied

#### Addition Information/Debugging Steps:
The issue is with the following line in the replace_or_append function: `eval '$sed_command "s/$key.*/$formatted_output/g" $config_file'`

Somehow, the assignment of IFS (internal field separator) variable to `IFS=$'\n'` in the remediation for xccdf_org.ssgproject.content_rule_ensure_redhat_gpgkey_installed breaks the eval statement in the replace_or_append function in any subsequent remediations.

### PR DESCRIPTION
**Pull request by nathanpeters008**
#### Description:

Reset IFS back to default in ensure_redhat_gpgkey_installed.sh to avoid breaking subsequent remediations.

#### Rationale:

Line 15 of shared/fixes/bash/ensure_redhat_gpgkey_installed.sh sets IFS (the Internal Field Separator special environment variable) to `$'\n'` from its default of `<tab><space><newline>`.

If not reset to default after this, and remediations are run in a single script, any eval that starts with `sed -i` in subsequent remediations will fail with the message `sed -i: command not found` due to the fact that the eval expects `<space>` in the Internal Field Separator list.

- Fixes #2511

### CODE REVIEW

**Comment by redhatrises** [comment]
@nathanpeters008 would you be willing to check all scripts to make sure that IFS is unset and add those fixes to this PR?

File: shared/fixes/bash/ensure_redhat_gpgkey_installed.sh [hunk 1]
```diff
@@ -14,6 +14,8 @@ then
   # (to ensure there won't be e.g. CRC error).
   IFS=$'\n' GPG_OUT=($(gpg --with-fingerprint "${REDHAT_RELEASE_KEY}" | grep 'Key fingerprint ='))
```
Comment (mpreisler) [inline shared/fixes/bash/ensure_redhat_gpgkey_installed.sh]: Wouldn't it be more elegant to set the IFS inside the subshell? That way there is no need to unset it.

Comment (nathanpeters008) [reply shared/fixes/bash/ensure_redhat_gpgkey_installed.sh]: @redhatrises I had already grepped the code base for unmatched instances of IFS= that didn't have a corresponding unset IFS before submitting this.  The one exception is shared/bash_remediation_functions/perform_audit_rules_privileged_commands_remediation.sh but I don't really have time to make that change and confirm that I didn't accidentally break anything.

@mpreisler if someone else wants to take the effort to rewrite these statements they are welcome to.  I'm limiting the scope of fixes to things that affect remediations I am running on my systems due to limited time.  I was keeping this fix similar to how the IFS / unset IFS behavior is already implemented in other scripts to avoid additional troubleshooting time.

File: shared/fixes/bash/ensure_redhat_gpgkey_installed.sh [hunk 2]
```diff
@@ -14,6 +14,8 @@ then
...
   GPG_RESULT=$?
+  # Reset IFS back to default
+  unset $IFS
```
Comment (yuumasato) [inline shared/fixes/bash/ensure_redhat_gpgkey_installed.sh]: Shouldn't this be just `unset IFS`?

Comment (nathanpeters008) [reply shared/fixes/bash/ensure_redhat_gpgkey_installed.sh]: Interesting point.  It looks like I was working from an old code base, which upon further examination, was inconsistent in the use of the unset command:
```
# grep 'unset IFS' *
audit_rules_execution_chcon.sh:	unset IFS
audit_rules_execution_chcon.sh:	unset IFS
audit_rules_execution_chcon.sh:				unset IFS
audit_rules_execution_restorecon.sh:	unset IFS
audit_rules_execution_restorecon.sh:	unset IFS
audit_rules_execution_restorecon.sh:				unset IFS
audit_rules_execution_semanage.sh:	unset IFS
audit_rules_execution_semanage.sh:	unset IFS
audit_rules_execution_semanage.sh:				unset IFS
audit_rules_execution_setsebool.sh:	unset IFS
audit_rules_execution_setsebool.sh:	unset IFS
audit_rules_execution_setsebool.sh:				unset IFS
audit_rules_login_events_faillock.sh:	unset IFS
audit_rules_login_events_lastlog.sh:	unset IFS
audit_rules_login_events_tallylog.sh:	unset IFS
audit_rules_privileged_commands_chage.sh:	unset IFS
audit_rules_privileged_commands_chage.sh:	unset IFS
audit_rules_privileged_commands_chage.sh:				unset IFS
audit_rules_privileged_commands_chsh.sh:	unset IFS
audit_rules_privileged_commands_chsh.sh:	unset IFS
audit_rules_privileged_commands_chsh.sh:				unset IFS
audit_rules_privileged_commands_crontab.sh:	unset IFS
audit_rules_privileged_commands_crontab.sh:	unset IFS
audit_rules_privileged_commands_crontab.sh:				unset IFS
audit_rules_privileged_commands_gpasswd.sh:	unset IFS
audit_rules_privileged_commands_gpasswd.sh:	unset IFS
audit_rules_privileged_commands_gpasswd.sh:				unset IFS
audit_rules_privileged_commands_newgrp.sh:	unset IFS
audit_rules_privileged_commands_newgrp.sh:	unset IFS
audit_rules_privileged_commands_newgrp.sh:				unset IFS
audit_rules_privileged_commands_pam_timestamp_check.sh:	unset IFS
audit_rules_privileged_commands_pam_timestamp_check.sh:	unset IFS
audit_rules_privileged_commands_pam_timestamp_check.sh:				unset IFS
audit_rules_privileged_commands_passwd.sh:	unset IFS
audit_rules_privileged_commands_passwd.sh:	unset IFS
audit_rules_privileged_commands_passwd.sh:				unset IFS
audit_rules_privileged_commands_postdrop.sh:	unset IFS
audit_rules_privileged_commands_postdrop.sh:	unset IFS
audit_rules_privileged_commands_postdrop.sh:				unset IFS
audit_rules_privileged_commands_postqueue.sh:	unset IFS
audit_rules_privileged_commands_postqueue.sh:	unset IFS
audit_rules_privileged_commands_postqueue.sh:				unset IFS
audit_rules_privileged_commands_ssh_keysign.sh:	unset IFS
audit_rules_privileged_commands_ssh_keysign.sh:	unset IFS
audit_rules_privileged_commands_ssh_keysign.sh:				unset IFS
audit_rules_privileged_commands_sudoedit.sh:	unset IFS
audit_rules_privileged_commands_sudoedit.sh:	unset IFS
audit_rules_privileged_commands_sudoedit.sh:				unset IFS
audit_rules_privileged_commands_sudo.sh:	unset IFS
audit_rules_privileged_commands_sudo.sh:	unset IFS
audit_rules_privileged_commands_sudo.sh:				unset IFS
audit_rules_privileged_commands_su.sh:	unset IFS
audit_rules_privileged_commands_su.sh:	unset IFS
audit_rules_privileged_commands_su.sh:				unset IFS
audit_rules_privileged_commands_umount.sh:	unset IFS
audit_rules_privileged_commands_umount.sh:	unset IFS
audit_rules_privileged_commands_umount.sh:				unset IFS
audit_rules_privileged_commands_unix_chkpwd.sh:	unset IFS
audit_rules_privileged_commands_unix_chkpwd.sh:	unset IFS
audit_rules_privileged_commands_unix_chkpwd.sh:				unset IFS
audit_rules_privileged_commands_userhelper.sh:	unset IFS
audit_rules_privileged_commands_userhelper.sh:	unset IFS
audit_rules_privileged_commands_userhelper.sh:				unset IFS
# grep 'unset $IFS' *
audit_rules_dac_modification_chmod.sh:        unset $IFS
audit_rules_dac_modification_chmod.sh:        unset $IFS
audit_rules_dac_modification_chmod.sh:                                unset $IFS
audit_rules_dac_modification_chown.sh:        unset $IFS
audit_rules_dac_modification_chown.sh:        unset $IFS
audit_rules_dac_modification_chown.sh:                                unset $IFS
audit_rules_dac_modification_fchmodat.sh:        unset $IFS
audit_rules_dac_modification_fchmodat.sh:        unset $IFS
audit_rules_dac_modification_fchmodat.sh:                                unset $IFS
audit_rules_dac_modification_fchmod.sh:        unset $IFS
audit_rules_dac_modification_fchmod.sh:        unset $IFS
audit_rules_dac_modification_fchmod.sh:                                unset $IFS
audit_rules_dac_modification_fchownat.sh:        unset $IFS
audit_rules_dac_modification_fchownat.sh:        unset $IFS
audit_rules_dac_modification_fchownat.sh:                                unset $IFS
audit_rules_dac_modification_fchown.sh:        unset $IFS
audit_rules_dac_modification_fchown.sh:        unset $IFS
audit_rules_dac_modification_fchown.sh:                                unset $IFS
audit_rules_dac_modification_fremovexattr.sh:        unset $IFS
audit_rules_dac_modification_fremovexattr.sh:        unset $IFS
audit_rules_dac_modification_fremovexattr.sh:                                unset $IFS
audit_rules_dac_modification_fsetxattr.sh:        unset $IFS
audit_rules_dac_modification_fsetxattr.sh:        unset $IFS
audit_rules_dac_modification_fsetxattr.sh:                                unset $IFS
audit_rules_dac_modification_lchown.sh:        unset $IFS
audit_rules_dac_modification_lchown.sh:        unset $IFS
audit_rules_dac_modification_lchown.sh:                                unset $IFS
audit_rules_dac_modification_lremovexattr.sh:        unset $IFS
audit_rules_dac_modification_lremovexattr.sh:        unset $IFS
audit_rules_dac_modification_lremovexattr.sh:                                unset $IFS
audit_rules_dac_modification_lsetxattr.sh:        unset $IFS
audit_rules_dac_modification_lsetxattr.sh:        unset $IFS
audit_rules_dac_modification_lsetxattr.sh:                                unset $IFS
audit_rules_dac_modification_removexattr.sh:        unset $IFS
audit_rules_dac_modification_removexattr.sh:        unset $IFS
audit_rules_dac_modification_removexattr.sh:                                unset $IFS
audit_rules_dac_modification_setxattr.sh:        unset $IFS
audit_rules_dac_modification_setxattr.sh:        unset $IFS
audit_rules_dac_modification_setxattr.sh:                                unset $IFS
audit_rules_file_deletion_events.sh:        unset $IFS
audit_rules_file_deletion_events.sh:        unset $IFS
audit_rules_file_deletion_events.sh:                                unset $IFS
audit_rules_kernel_module_loading.sh:        unset $IFS
audit_rules_kernel_module_loading.sh:        unset $IFS
audit_rules_kernel_module_loading.sh:                                unset $IFS
audit_rules_kernel_module_loading.sh:        unset $IFS
audit_rules_kernel_module_loading.sh:        unset $IFS
audit_rules_kernel_module_loading.sh:        unset $IFS
audit_rules_login_events.sh:        unset $IFS
audit_rules_login_events.sh:        unset $IFS
audit_rules_login_events.sh:        unset $IFS
audit_rules_mac_modification.sh:        unset $IFS
audit_rules_media_export.sh:        unset $IFS
audit_rules_media_export.sh:        unset $IFS
audit_rules_media_export.sh:                                unset $IFS
audit_rules_networkconfig_modification.sh:        unset $IFS
audit_rules_networkconfig_modification.sh:        unset $IFS
audit_rules_networkconfig_modification.sh:                                unset $IFS
audit_rules_networkconfig_modification.sh:        unset $IFS
audit_rules_networkconfig_modification.sh:        unset $IFS
audit_rules_networkconfig_modification.sh:        unset $IFS
audit_rules_networkconfig_modification.sh:        unset $IFS
audit_rules_session_events.sh:        unset $IFS
audit_rules_session_events.sh:        unset $IFS
audit_rules_session_events.sh:        unset $IFS
audit_rules_sysadmin_actions.sh:        unset $IFS
audit_rules_time_adjtimex.sh:        unset $IFS
audit_rules_time_adjtimex.sh:        unset $IFS
audit_rules_time_adjtimex.sh:                                unset $IFS
audit_rules_time_clock_settime.sh:        unset $IFS
audit_rules_time_clock_settime.sh:        unset $IFS
audit_rules_time_clock_settime.sh:                                unset $IFS
audit_rules_time_settimeofday.sh:        unset $IFS
audit_rules_time_settimeofday.sh:        unset $IFS
audit_rules_time_settimeofday.sh:                                unset $IFS
audit_rules_time_stime.sh:        unset $IFS
audit_rules_time_stime.sh:        unset $IFS
audit_rules_time_stime.sh:                                unset $IFS
audit_rules_time_watch_localtime.sh:        unset $IFS
audit_rules_unsuccessful_file_modification.sh:        unset $IFS
audit_rules_unsuccessful_file_modification.sh:        unset $IFS
audit_rules_unsuccessful_file_modification.sh:                                unset $IFS
audit_rules_unsuccessful_file_modification.sh:        unset $IFS
audit_rules_unsuccessful_file_modification.sh:        unset $IFS
audit_rules_unsuccessful_file_modification.sh:                                unset $IFS
audit_rules_usergroup_modification.sh:        unset $IFS
audit_rules_usergroup_modification.sh:        unset $IFS
audit_rules_usergroup_modification.sh:        unset $IFS
audit_rules_usergroup_modification.sh:        unset $IFS
audit_rules_usergroup_modification.sh:        unset $IFS
```

Looking at the newest code base, it appears that unset IFS is the standard:
```
# grep -r 'unset IFS' *
shared/bash_remediation_functions/fix_audit_watch_rule.sh:	unset IFS
shared/bash_remediation_functions/fix_audit_syscall_rule.sh:	unset IFS
shared/bash_remediation_functions/fix_audit_syscall_rule.sh:	unset IFS
shared/bash_remediation_functions/fix_audit_syscall_rule.sh:				unset IFS
# grep -r 'unset $IFS' *
# 

```

**Comment by nathanpeters008** [comment]
Switched to `unset IFS` after reviewing newest code base and reading comment by @yuumasato

File: shared/fixes/bash/ensure_redhat_gpgkey_installed.sh (hunk 1 above)
Comment (mpreisler) [reply shared/fixes/bash/ensure_redhat_gpgkey_installed.sh]: ok, makes sense to keep all of these patterns the same then

**Comment by mpreisler** [comment]
ACK
